// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BkzVjNxpFxao5yD2iUB-24bCifQNOmU',
    appId: '1:368493790762:web:69cf63eb545c2f3fac6553',
    messagingSenderId: '368493790762',
    projectId: 'chat-app-343fb',
    authDomain: 'chat-app-343fb.firebaseapp.com',
    storageBucket: 'chat-app-343fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftR1q6UTAZ9-ItXxh8IHgIoVpQRH8Cvk',
    appId: '1:368493790762:android:095c507948289c5aac6553',
    messagingSenderId: '368493790762',
    projectId: 'chat-app-343fb',
    storageBucket: 'chat-app-343fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu29q-BuzVGq9arjMfNAw3zBhUq547Jyk',
    appId: '1:368493790762:ios:85db1aad0a8dc596ac6553',
    messagingSenderId: '368493790762',
    projectId: 'chat-app-343fb',
    storageBucket: 'chat-app-343fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu29q-BuzVGq9arjMfNAw3zBhUq547Jyk',
    appId: '1:368493790762:ios:4cd5c35ddf883633ac6553',
    messagingSenderId: '368493790762',
    projectId: 'chat-app-343fb',
    storageBucket: 'chat-app-343fb.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
